# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spaceship.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fspaceship.proto\"\xf7\x01\n\x0b\x43oordinates\x12\x34\n\x0fright_ascention\x18\x01 \x02(\x0b\x32\x1b.Coordinates.RightAscention\x12-\n\x0b\x64\x65\x63lination\x18\x02 \x02(\x0b\x32\x18.Coordinates.Declination\x1a\x41\n\x0eRightAscention\x12\r\n\x05hours\x18\x01 \x02(\x05\x12\x0f\n\x07minutes\x18\x02 \x02(\x05\x12\x0f\n\x07seconds\x18\x03 \x02(\x02\x1a@\n\x0b\x44\x65\x63lination\x12\x0f\n\x07\x64\x65grees\x18\x01 \x02(\x05\x12\x0f\n\x07minutes\x18\x02 \x02(\x05\x12\x0f\n\x07seconds\x18\x03 \x02(\x02\">\n\x07Officer\x12\x12\n\nfirst_name\x18\x01 \x02(\t\x12\x11\n\tlast_name\x18\x02 \x02(\t\x12\x0c\n\x04rank\x18\x03 \x02(\t\"\xb6\x02\n\tSpaceship\x12\'\n\talignment\x18\x01 \x02(\x0e\x32\x14.Spaceship.Alignment\x12\x0c\n\x04name\x18\x02 \x02(\t\x12$\n\nship_class\x18\x03 \x02(\x0e\x32\x10.Spaceship.Class\x12\x0e\n\x06length\x18\x04 \x02(\x02\x12\x11\n\tcrew_size\x18\x05 \x02(\x05\x12\r\n\x05\x61rmed\x18\x06 \x02(\x08\x12\x1a\n\x08officers\x18\x07 \x03(\x0b\x32\x08.Officer\" \n\tAlignment\x12\x08\n\x04\x41lly\x10\x00\x12\t\n\x05\x45nemy\x10\x01\"\\\n\x05\x43lass\x12\x0c\n\x08\x43orvette\x10\x00\x12\x0b\n\x07\x46rigate\x10\x01\x12\x0b\n\x07\x43ruiser\x10\x02\x12\r\n\tDestroyer\x10\x03\x12\x0b\n\x07\x43\x61rrier\x10\x04\x12\x0f\n\x0b\x44readnought\x10\x05\x32\x42\n\x10SpaceshipService\x12.\n\x10GetSpaceshipInfo\x12\x0c.Coordinates\x1a\n.Spaceship0\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spaceship_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_COORDINATES']._serialized_start=20
  _globals['_COORDINATES']._serialized_end=267
  _globals['_COORDINATES_RIGHTASCENTION']._serialized_start=136
  _globals['_COORDINATES_RIGHTASCENTION']._serialized_end=201
  _globals['_COORDINATES_DECLINATION']._serialized_start=203
  _globals['_COORDINATES_DECLINATION']._serialized_end=267
  _globals['_OFFICER']._serialized_start=269
  _globals['_OFFICER']._serialized_end=331
  _globals['_SPACESHIP']._serialized_start=334
  _globals['_SPACESHIP']._serialized_end=644
  _globals['_SPACESHIP_ALIGNMENT']._serialized_start=518
  _globals['_SPACESHIP_ALIGNMENT']._serialized_end=550
  _globals['_SPACESHIP_CLASS']._serialized_start=552
  _globals['_SPACESHIP_CLASS']._serialized_end=644
  _globals['_SPACESHIPSERVICE']._serialized_start=646
  _globals['_SPACESHIPSERVICE']._serialized_end=712
# @@protoc_insertion_point(module_scope)
